(add-to-list 'load-path "~/.emacs.d")
(require 'linum)
;;; (require 'auto-complete-extension)
(global-linum-mode 1)
(defun linum-format-func (line)
  (let ((w (length (number-to-string (count-lines (point-min) (point-max))))))
     (propertize (format (format "%%%dd " w) line) 'face 'linum)))
(setq linum-format 'linum-format-func)
(define-key global-map (kbd "RET") 'newline-and-indent)
